#!/bin/bash

if [ -d $HOME/.xmonad ]; then
    themeName=$(awk -F '[ .]' '/import Colors/{print $3}' $HOME/.xmonad/xmonad.hs);
    colorDir="$HOME/.xmonad/lib/Colors";
fi;

if [ -d $colorDir ] && [ -f $colorDir/$themeName.hs ]; then
  if [ ! -d Colors ]; then
      echo "Copy $colorDir";
      cp -r $HOME/.xmonad/lib/Colors ./Colors
  fi;
  if grep -q "import Colors" XMobarConf.hs
  then
      sed -i "s/import Colors.*/import Colors.$themeName/" XMobarConf.hs
  else 
      sed -i "s/import XMobarConfGenerator/import XMobarConfGenerator\nimport Colors.$themeName/" XMobarConf.hs
  fi;
fi;
